# Generated by Django 4.2.7 on 2026-06-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='question',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='session_id',
        ),
    ]
