# Generated by Django 4.2.7 on 2026-06-29 12:49

import backend.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0002_remove_chathistory_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=backend.supabase_storage.ImageStorage(), upload_to='incidents/thumbnails/'),
        ),
    ]
