# Generated by Django 4.2.7 on 2026-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0003_incident_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='activity_sector',
            field=models.CharField(blank=True, choices=[('environment', 'Environnement'), ('sanitation', 'Assainissement'), ('water_wash', 'Eau / WASH'), ('health', 'Santé'), ('food_security', 'Sécurité alimentaire'), ('protection', 'Protection'), ('humanitarian', 'Humanitaire'), ('development', 'Développement'), ('governance', 'Gouvernance'), ('education', 'Éducation'), ('technology_data', 'Technologie / Données'), ('multisector', 'Multisectoriel'), ('other', 'Autre')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('ngo', 'ONG'), ('international_organisation', 'Organisation internationale'), ('un_agency', 'Agence UN'), ('public_institution', 'Institution publique'), ('local_authority', 'Collectivité territoriale'), ('association_cso', 'Association / OSC'), ('private_sector', 'Secteur privé'), ('project_program', 'Projet / Programme'), ('community_structure', 'Structure communautaire'), ('other', 'Autre')], max_length=40, null=True),
        ),
    ]
