# Generated by Django 4.2.7 on 2026-06-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0004_alter_organisation_activity_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Mapapi.incident'),
        ),
    ]
