# Generated by Django 4.2.7 on 2026-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0005_notification_incident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraction',
            options={'ordering': ('-created_at', '-timeStamp')},
        ),
        migrations.AddField(
            model_name='useraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
