# Generated by Django 4.2.7 on 2026-06-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0006_alter_useraction_options_useraction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
