# Generated by Django 4.2.7 on 2026-06-21 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0025_incident_take_in_charge_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Motif de refus de la résolution par le Super Admin.', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Date de soumission du dossier de résolution préparée.', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution_submitted_by',
            field=models.ForeignKey(blank=True, help_text='Membre (agent de bureau/admin) ayant monté le dossier de résolution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='validation_deadline',
            field=models.DateTimeField(blank=True, help_text='Échéance de contrôle Super Admin (72h après déclaration de résolution).', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='etat',
            field=models.CharField(choices=[('declared', 'declared'), ('resolved', 'resolved'), ('in_progress', 'in_progress'), ('taken_into_account', 'taken_into_account'), ('resolution_prepared', 'Résolution préparée (attente Admin)'), ('in_validation', 'Résolu (en validation)'), ('resolved_definitive', 'Résolu (définitif)')], default='declared', max_length=255),
        ),
    ]
