# Generated by Django 4.2.7 on 2026-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0026_incident_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de la mise en corbeille (is_deleted=True). Sert à la purge des 30 j (spec D10).', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='taken_in_charge_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage de la prise en compte (passage en 'taken_into_account'). Sert au calcul du délai anti-gel (spec T3).", null=True),
        ),
    ]
