# Generated by Django 4.2.7 on 2026-06-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0027_incident_deleted_at_incident_taken_in_charge_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='colaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mapapi.collaboration'),
        ),
    ]
