# Generated by Django 4.2.7 on 2026-06-21 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0028_alter_notification_colaboration'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentOrgAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Déclinée')], default='pending', max_length=20)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(help_text="Échéance d'acceptation (now + 72 h).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_org_assignments', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_assignments', to='Mapapi.incident')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mapapi.organisation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
