# Generated by Django 4.2.7 on 2026-06-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0029_incidentorgassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='antigel_warned_75',
            field=models.BooleanField(default=False, help_text='Avertissement anti-gel à 75 % du délai déjà envoyé au leader. Remis à False à chaque (re)prise en compte (spec T3).'),
        ),
        migrations.AddField(
            model_name='incident',
            name='antigel_warned_90',
            field=models.BooleanField(default=False, help_text='Avertissement anti-gel à 90 % du délai déjà envoyé au leader. Remis à False à chaque (re)prise en compte (spec T3).'),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(blank=True, choices=[('high', 'Élevée'), ('medium', 'Moyenne'), ('low', 'Faible')], default='medium', help_text='Sévérité catégorielle. Pilote le délai anti-gel (Élevée 30 j / Moyenne 60 j / Faible 90 j ; défaut/inconnue : 60 j).', max_length=10, null=True),
        ),
    ]
